name: Build Go-API
run-name: ${{ github.actor }} is building Go-API ✈️
on:
  push:
    branches:
      - main
jobs:
  make-swag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Swag
        run: |
          cd golang_backend
          go mod download
          swag init -g cmd/main.go
